### PR TITLE
DE34261: Fixed escape key event handler

### PR DESCRIPTION
**Pull request by lvyuan95-d2l**
Escape key event doesn't seem to register successfully in the current version (tested with `demo/index.html` and other shared components), switched to `iron-a11y-keys` and it worked fine now.

### CODE REVIEW

**Comment by lvyuan95-d2l** [comment]
If you can merge the PR for me that would be great, thanks!

**Comment by dlockhart** [comment]
Can you wait a minute before merging? I'd like to look into this more... all the `iron-*` components aren't moving forward to Lit so it'd be great to understand what's actually going on here.

**Comment by MichaelKovalchuk** [comment]
travis does not succeed

**Comment by lvyuan95-d2l** [comment]
> travis does not succeed

Is there any way to retrigger the CI? I don't think it has anything to do with the code.

**Comment by dlockhart** [comment]
I've tried re-triggering a couple times and it's getting the same error. It's failing on the `oracle-java8-installer` which is used for the Galen tests. @awikkerink I seem to recall getting this error in the past and it usually clears up in a couple days... do you remember any other details about it?

**Comment by dbatiste** [comment]
Any info on what was happening here?  For what it's worth, [d2l-dropdown](https://github.com/BrightspaceUI/dropdown/blob/master/d2l-dropdown-content-behavior.js#L494) listens for keyup on the target.

**Comment by lvyuan95-d2l** [comment]
> Any info on what was happening here? For what it's worth, [d2l-dropdown](https://github.com/BrightspaceUI/dropdown/blob/master/d2l-dropdown-content-behavior.js#L494) listens for **keyup** on the target.


When tooltip shows I don't think the focus will be on the tooltip, therefore the `keydown` event willl not be triggered.

**Comment by dbatiste** [comment]
Ah I see, thanks.  Is the target of the tooltip supposed to be focusable, or is it valid for the target to be something non-interactive?  If the target is supposed to be focusable, I think I would have expected that element to get the wire-up.

Should this still get wired up when `force-show` is being used?  This raises the question of whether there can be more than one tooltip displayed at once, and if so, should escape hide them all?

**Comment by lvyuan95-d2l** [comment]
> Ah I see, thanks. Is the target of the tooltip supposed to be focusable, or is it valid for the target to be something non-interactive? If the target is supposed to be focusable, I think I would have expected that element to get the wire-up.
> 
> Should this still get wired up when `force-show` is being used? This raises the question of whether there can be more than one tooltip displayed at once, and if so, should escape hide them all?

From what I've tested with `demo/index.html`, even with the target being focused, somehow the tooltip still won't be hidden.

In this case, I believe that correct behavior is that, even without the target being focused, the tooltip still should hide when pressing `esc`, for example, when the user hovers the mouse on a certain text, the tooltip shows, and then the user presses `esc` key, which hides the tooltip. However, the current implementation seems to assume that the user already clicked on the text, before the `keydown`  event can be fired.

Also for `force-show` case, I ran a few tests and it seems that with `force-show` flag, the component won't trigger `show()` and `hide()` function, and therefore will not register the `keydown` event. So I think the changes would be fine in this case.

**Pull request merged**
